-- Ejecutar después de 004_admin_management.sql. Roles y separación estricta por empresa.
begin;
create table public.companies(id uuid primary key default gen_random_uuid(),name text not null unique check(length(name) between 2 and 150),active boolean not null default true,created_at timestamptz not null default now());
alter table public.companies enable row level security;
create policy companies_read on public.companies for select to anon,authenticated using(active or exists(select 1 from public.admins where user_id=auth.uid()));
grant select on public.companies to anon,authenticated;
alter table public.profiles add column company_id uuid references public.companies(id);
create table public.access_roles(user_id uuid primary key references auth.users(id) on delete cascade,role text not null check(role in ('developer','admin','user')),company_id uuid references public.companies(id),check(role='developer' or company_id is not null));
alter table public.access_roles enable row level security;
revoke all on public.access_roles from anon,authenticated;
grant select on public.access_roles to authenticated;
create function public.is_developer() returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.access_roles where user_id=auth.uid() and role='developer')$$;
create function public.current_company_id() returns uuid language sql stable security definer set search_path='' as $$select company_id from public.access_roles where user_id=auth.uid()$$;
create function public.can_manage(p_user uuid) returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.access_roles me left join public.access_roles other on other.user_id=p_user where me.user_id=auth.uid() and (me.role='developer' or (me.role='admin' and me.company_id=other.company_id)))$$;
create or replace function public.is_admin() returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.access_roles where user_id=auth.uid() and role in ('developer','admin'))$$;
create function public.access_context() returns jsonb language sql stable security definer set search_path='' as $$select jsonb_build_object('role',r.role,'company_id',r.company_id,'company',c.name) from public.access_roles r left join public.companies c on c.id=r.company_id where r.user_id=auth.uid()$$;
create function public.list_companies() returns jsonb language sql stable security definer set search_path='' as $$select coalesce(jsonb_agg(jsonb_build_object('id',id,'name',name) order by name),'[]'::jsonb) from public.companies where active$$;
create function public.developer_create_company(p_name text) returns uuid language plpgsql security definer set search_path='' as $$declare cid uuid;begin if not public.is_developer() then raise exception 'Solo el desarrollador puede crear empresas.';end if;insert into public.companies(name) values(left(trim(p_name),150)) returning id into cid;return cid;end$$;
create function public.developer_assign_role(p_email text,p_role text,p_company uuid default null) returns void language plpgsql security definer set search_path='' as $$declare uid uuid;begin if not public.is_developer() then raise exception 'Solo el desarrollador puede asignar accesos.';end if;if p_role not in ('admin','user') then raise exception 'Rol no válido.';end if;if p_company is null then raise exception 'Selecciona una empresa.';end if;select id into uid from auth.users where lower(email)=lower(trim(p_email));if uid is null then raise exception 'El correo aún no tiene una cuenta confirmada.';end if;insert into public.access_roles(user_id,role,company_id) values(uid,p_role,p_company) on conflict(user_id) do update set role=excluded.role,company_id=excluded.company_id;update public.profiles set company_id=p_company,company=(select name from public.companies where id=p_company) where id=uid;end$$;
revoke all on function public.is_developer(),public.current_company_id(),public.can_manage(uuid),public.access_context(),public.developer_create_company(text),public.developer_assign_role(text,text,uuid) from public;
grant execute on function public.is_developer(),public.current_company_id(),public.can_manage(uuid),public.access_context(),public.developer_create_company(text),public.developer_assign_role(text,text,uuid) to authenticated;
revoke all on function public.list_companies() from public;grant execute on function public.list_companies() to anon,authenticated;
drop policy if exists profile_read on public.profiles;drop policy if exists profile_update on public.profiles;drop policy if exists entries_access on public.entries;drop policy if exists rests_access on public.rests;drop policy if exists audit_read on public.audit_log;
create policy profile_read on public.profiles for select to authenticated using(id=auth.uid() or public.can_manage(id));
create policy profile_update on public.profiles for update to authenticated using(id=auth.uid() or public.can_manage(id)) with check(id=auth.uid() or public.can_manage(id));
create policy entries_access on public.entries for all to authenticated using(user_id=auth.uid() or public.can_manage(user_id)) with check(user_id=auth.uid() or public.can_manage(user_id));
create policy rests_access on public.rests for all to authenticated using(user_id=auth.uid() or public.can_manage(user_id)) with check(user_id=auth.uid() or public.can_manage(user_id));
create policy audit_read on public.audit_log for select to authenticated using(user_id=auth.uid() or public.can_manage(user_id));
create policy roles_read on public.access_roles for select to authenticated using(user_id=auth.uid() or public.can_manage(user_id));
create or replace function public.new_user_profile() returns trigger language plpgsql security definer set search_path='' as $$declare cid uuid;declare assigned_role text;begin cid:=nullif(new.raw_user_meta_data->>'company_id','')::uuid;assigned_role:=case when lower(coalesce(new.email,''))='mespinozahse@gmail.com' then 'developer' else 'user' end;insert into public.profiles(id,name,first_name,last_name,company,company_id,document_type,document_number,phone,email) values(new.id,left(trim(concat(coalesce(new.raw_user_meta_data->>'first_name',''),' ',coalesce(new.raw_user_meta_data->>'last_name',''))),100),left(coalesce(new.raw_user_meta_data->>'first_name',''),80),left(coalesce(new.raw_user_meta_data->>'last_name',''),100),coalesce((select name from public.companies where id=cid),''),cid,case when new.raw_user_meta_data->>'document_type'='CE' then 'CE' else 'DNI' end,left(regexp_replace(coalesce(new.raw_user_meta_data->>'document_number',''),'[^0-9A-Za-z-]','','g'),15),left(coalesce(new.raw_user_meta_data->>'phone',''),30),coalesce(new.email,''));insert into public.access_roles(user_id,role,company_id) values(new.id,assigned_role,case when assigned_role='developer' then null else cid end);return new;end$$;
-- Si la cuenta del desarrollador ya existe, vincularla de forma segura.
insert into public.access_roles(user_id,role,company_id) select id,'developer',null from auth.users where lower(email)='mespinozahse@gmail.com' and email_confirmed_at is not null on conflict(user_id) do update set role='developer',company_id=null;
alter function public.admin_dashboard() rename to admin_dashboard_unfiltered;
revoke all on function public.admin_dashboard_unfiltered() from public,anon,authenticated;
create function public.admin_dashboard() returns jsonb language plpgsql stable security definer set search_path='' as $$declare d jsonb;declare cid uuid;begin if not public.is_admin() then raise exception 'Solo el administrador puede consultar las estadísticas.';end if;d:=public.admin_dashboard_unfiltered();if public.is_developer() then return d;end if;cid:=public.current_company_id();d:=jsonb_set(d,'{registered}',to_jsonb((select count(*) from public.access_roles where company_id=cid)));d:=jsonb_set(d,'{entries}',to_jsonb((select count(*) from public.entries e join public.access_roles r on r.user_id=e.user_id where r.company_id=cid)));d:=jsonb_set(d,'{earned}',to_jsonb((select coalesce(sum(e.minutes),0) from public.entries e join public.access_roles r on r.user_id=e.user_id where r.company_id=cid)));d:=jsonb_set(d,'{used}',to_jsonb((select coalesce(sum(x.minutes),0) from public.rests x join public.access_roles r on r.user_id=x.user_id where r.company_id=cid and x.status='taken')));d:=jsonb_set(d,'{reserved}',to_jsonb((select coalesce(sum(x.minutes),0) from public.rests x join public.access_roles r on r.user_id=x.user_id where r.company_id=cid and x.status='approved')));d:=jsonb_set(d,'{directory}',coalesce((select jsonb_agg(v) from jsonb_array_elements(d->'directory') v where public.can_manage((v->>'id')::uuid)),'[]'::jsonb));d:=jsonb_set(d,'{pending}',coalesce((select jsonb_agg(v) from jsonb_array_elements(d->'pending') v where public.can_manage((v->>'user_id')::uuid)),'[]'::jsonb));d:=jsonb_set(d,'{rests}',coalesce((select jsonb_agg(v) from jsonb_array_elements(d->'rests') v where public.can_manage((v->>'user_id')::uuid)),'[]'::jsonb));d:=jsonb_set(d,'{audit}',coalesce((select jsonb_agg(v) from jsonb_array_elements(d->'audit') v where public.can_manage((v->>'user_id')::uuid)),'[]'::jsonb));return d;end$$;
revoke all on function public.admin_dashboard() from public;grant execute on function public.admin_dashboard() to authenticated;
commit;

