export const VERSION='1.2.0';
export const defaults={name:'',company:'',phone:'',dayHours:8,schedule:['','16:00','16:00','17:00','17:00','17:00','12:00']};
export function limaNow(now=new Date()){const p=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:'America/Lima',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(now).map(x=>[x.type,x.value]));return {date:`${p.year}-${p.month}-${p.day}`,time:`${p.hour}:${p.minute}`};}
export function weekday(date){return new Date(date+'T12:00:00Z').getUTCDay();}
export function validDate(date){return /^\d{4}-\d{2}-\d{2}$/.test(date)&&!isNaN(Date.parse(date))&&new Date(date+'T12:00:00Z').toISOString().slice(0,10)===date;}
export function timeMinutes(time){if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(time))throw Error('Ingresa una hora válida.');return Number(time.slice(0,2))*60+Number(time.slice(3));}
export function extraMinutes(r){const start=timeMinutes(r.kind==='ordinary'?r.expected:r.start);const end=timeMinutes(r.end)+(r.nextDay?1440:0);const pause=Number(r.pause||0);if(!Number.isInteger(pause)||pause<0||pause>1440)throw Error('La pausa debe ser un número de minutos válido.');if(r.kind!=='ordinary'&&end<=start)throw Error('La salida debe ser posterior al inicio; marca el día siguiente si corresponde.');const span=Math.max(0,end-start);if(span>1440)throw Error('El intervalo no puede superar 24 horas.');if(pause>span)throw Error('La pausa supera el intervalo registrado.');return span-pause;}
export function duration(n){const sign=n<0?'−':'';n=Math.abs(Math.round(n));return `${sign}${Math.floor(n/60)} h ${String(n%60).padStart(2,'0')} min`;}
export function dayEquivalent(n,h=8){const unit=Math.round(h*60);return {days:Math.floor(Math.max(0,n)/unit),remainder:Math.max(0,n)%unit,decimal:n/unit};}
export function totals(records,rests){const earned=records.reduce((n,r)=>n+r.minutes,0);const used=rests.filter(x=>x.status==='taken').reduce((n,r)=>n+r.minutes,0);const reserved=rests.filter(x=>x.status==='approved').reduce((n,r)=>n+r.minutes,0);return {earned,used,reserved,balance:earned-used,available:earned-used-reserved};}
export function groupKey(date,mode){if(mode==='month')return date.slice(0,7);if(mode==='day')return date;const d=new Date(date+'T12:00:00Z');d.setUTCDate(d.getUTCDate()-((d.getUTCDay()+6)%7));return d.toISOString().slice(0,10);}
export function grouped(records,rests,mode){const map=new Map();const get=date=>{const key=groupKey(date,mode);if(!map.has(key))map.set(key,{period:key,earned:0,used:0,reserved:0});return map.get(key);};records.forEach(r=>get(r.date).earned+=r.minutes);rests.forEach(r=>{if(r.status==='taken')get(r.date).used+=r.minutes;if(r.status==='approved')get(r.date).reserved+=r.minutes;});return [...map.values()].sort((a,b)=>a.period.localeCompare(b.period));}
export const escapeHtml=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
