import {duration,grouped,totals,VERSION} from './core.js';
const statuses={requested:'Solicitado',approved:'Aprobado',taken:'Gozado',cancelled:'Cancelado'};
const types={ordinary:'Sobretiempo',restday:'Descanso semanal',holiday:'Feriado',special:'Atípico'};
export async function exportReport(format,{records,rests,profile,mode,from,to,chart,returnFile=false}){
 const groups=grouped(records,rests,mode),sum=totals(records,rests);const title='myk2 · Consolidado de tiempo';const period=`${from||'Inicio'} a ${to||'Hoy'} · Agrupación: ${{day:'día',week:'semana (lunes)',month:'mes'}[mode]}`;const detail=records.slice().sort((a,b)=>a.date.localeCompare(b.date)).map(r=>[r.date,types[r.kind],r.expected||'—',r.start||'—',r.end+(r.nextDay?' (+1 día)':''),r.pause||0,r.minutes/60,r.comment||'']);
 const restRows=rests.map(r=>[r.date,statuses[r.status],r.minutes/60,r.minutes/(profile.dayHours*60),r.comment||'']);
 if(format==='pdf'){
 const [{jsPDF},{default:autoTable}]=await Promise.all([import('jspdf'),import('jspdf-autotable')]);const doc=new jsPDF({orientation:'landscape'});const w=297;doc.setFillColor(23,44,49);doc.rect(0,0,w,37,'F');doc.setTextColor(196,237,117);doc.setFontSize(21);doc.text(title,14,16);doc.setTextColor(255);doc.setFontSize(10);doc.text(`${profile.name||'Usuario'}${profile.company?' · '+profile.company:''}`,14,25);doc.text(period,14,32);
 doc.setTextColor(23,44,49);doc.setFontSize(11);doc.text(`Generadas: ${duration(sum.earned)}     Gozadas: ${duration(sum.used)}     Reservadas: ${duration(sum.reserved)}`,14,46);doc.text(`Neto del período: ${duration(sum.balance)}  ·  Equivalencia referencial: ${profile.dayHours} h = 1 día`,14,54);
 let y=61;if(chart){doc.addImage(chart,'PNG',14,y,180,48);y+=55;}
 const table=(head,body,startY)=>autoTable(doc,{head:[head],body,startY,margin:{left:14,right:14,bottom:20},styles:{fontSize:9,cellPadding:3,overflow:'linebreak'},headStyles:{fillColor:[23,44,49],textColor:[255,255,255]},alternateRowStyles:{fillColor:[241,246,241]}});
 table(['Período','Generadas','Gozadas','Reservadas','Neto'],groups.map(r=>[r.period,duration(r.earned),duration(r.used),duration(r.reserved),duration(r.earned-r.used)]),y);
 doc.addPage();doc.setFontSize(16);doc.text('Detalle diario · horas decimales',14,18);table(['Fecha','Tipo','Salida prevista','Inicio','Salida real','Pausa min','Horas extra','Comentario'],detail.map(r=>r.map((v,i)=>i===6?v.toFixed(2):v)),25);
 if(restRows.length){doc.addPage();doc.text('Descansos compensatorios',14,18);table(['Fecha','Estado','Horas','Días equivalentes','Comentario'],restRows.map(r=>r.map((v,i)=>i===2||i===3?v.toFixed(2):v)),25);}
 const count=doc.getNumberOfPages();for(let i=1;i<=count;i++){doc.setPage(i);doc.setFontSize(8);doc.setTextColor(90);doc.text(`© Ing. Mauro Espinoza · myk2 · mespinozahse@gmail.com · +51 975721020 · v${VERSION}`,14,197);doc.text(`${i} / ${count}`,275,197);doc.text('Registro de compensación acordada; no es una liquidación laboral. Domingo/feriado se identifica por separado.',14,203);}
 if(returnFile)return new Uint8Array(doc.output('arraybuffer'));
 doc.save(`myk2-tiempo-${mode}-${to||'total'}.pdf`);return;
 }
 const {default:ExcelJS}=await import('exceljs');const book=new ExcelJS.Workbook();book.creator='Ing. Mauro Espinoza · myk2';book.created=new Date();
 const summary=book.addWorksheet('Resumen',{views:[{showGridLines:false}]});summary.columns=[{width:28},{width:24},{width:24},{width:24},{width:24}];summary.mergeCells('A1:E2');summary.getCell('A1').value=title;summary.getCell('A1').font={name:'Aptos Display',size:22,bold:true,color:{argb:'FFC4ED75'}};summary.getCell('A1').fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF172C31'}};summary.getCell('A1').alignment={vertical:'middle'};summary.mergeCells('A3:E3');summary.getCell('A3').value=`${profile.name||'Usuario'} · ${profile.company||''} · ${period}`;
 [['Horas generadas',sum.earned/60],['Horas gozadas',sum.used/60],['Horas reservadas',sum.reserved/60],['Neto del período (h)',sum.balance/60],['Equivalente neto (días)',sum.balance/(60*profile.dayHours)],['Horas por día',profile.dayHours]].forEach((r,i)=>{summary.getCell(i+5,1).value=r[0];summary.getCell(i+5,2).value=r[1];summary.getCell(i+5,2).numFmt='0.00';});
 const addTable=(sheet,name,ref,columns,rows)=>{sheet.addTable({name,ref,headerRow:true,style:{theme:'TableStyleMedium2',showRowStripes:true},columns:columns.map(name=>({name,filterButton:true})),rows});sheet.eachRow(row=>row.eachCell(cell=>{cell.font={...cell.font,name:'Aptos',size:11};cell.alignment={vertical:'middle',wrapText:true};}));sheet.views=[{state:'frozen',ySplit:1,showGridLines:false}];};
 addTable(summary,'Consolidado','A13',['Período','Generadas (h)','Gozadas (h)','Reservadas (h)','Neto (h)'],groups.map(r=>[r.period,r.earned/60,r.used/60,r.reserved/60,(r.earned-r.used)/60]));summary.views=[{showGridLines:false}];for(let r=14;r<14+groups.length;r++)for(let c=2;c<=5;c++)summary.getCell(r,c).numFmt='0.00';summary.getCell('A1').font={name:'Aptos Display',size:22,bold:true,color:{argb:'FFC4ED75'}};
 if(chart){const id=book.addImage({base64:chart,extension:'png'});summary.addImage(id,{tl:{col:0,row:16+groups.length},ext:{width:850,height:260}});}
 const daily=book.addWorksheet('Registro diario');daily.columns=[15,23,18,15,20,15,18,65].map(width=>({width}));addTable(daily,'Registro','A1',['Fecha','Tipo','Salida prevista','Inicio','Salida real','Pausa (min)','Extra (h)','Comentario'],detail);daily.getColumn(7).numFmt='0.00';
 const rest=book.addWorksheet('Descansos');rest.columns=[15,18,16,22,65].map(width=>({width}));addTable(rest,'Descansos','A1',['Fecha','Estado','Horas','Días equivalentes','Comentario'],restRows);rest.getColumn(3).numFmt='0.00';rest.getColumn(4).numFmt='0.00';
 const meta=book.addWorksheet('Acerca de');meta.getColumn(1).width=110;['© Ing. Mauro Espinoza · myk2','mespinozahse@gmail.com · +51 975721020',`Versión ${VERSION} · Zona horaria America/Lima`,`Equivalencia referencial: ${profile.dayHours} horas por día; compensación 1:1 según acuerdo.`, 'Los aprobados reservan saldo; solo los gozados descuentan.','Neto del período no incluye saldo de períodos anteriores.','Este informe no determina pagos, recargos ni validez de la jornada laboral.','Gráfico incorporado como imagen; datos editables en las tablas.'].forEach(x=>meta.addRow([x]));
 const buffer=await book.xlsx.writeBuffer();if(returnFile)return buffer;const blob=new Blob([buffer],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'});download(blob,`myk2-tiempo-${mode}-${to||'total'}.xlsx`);
}
export function download(blob,name){const old=document.getElementById('file-ready');if(old){URL.revokeObjectURL(old.dataset.url);old.remove();}const url=URL.createObjectURL(blob);const box=document.createElement('div');box.id='file-ready';box.dataset.url=url;box.className='file-ready';const a=document.createElement('a');a.href=url;a.download=name;a.textContent='Guardar '+name;const close=document.createElement('button');close.textContent='×';close.setAttribute('aria-label','Cerrar descarga');close.onclick=()=>{URL.revokeObjectURL(url);box.remove();};box.append(a,close);document.body.appendChild(box);a.dispatchEvent(new MouseEvent('click'));}
