import {VERSION} from './core.js';import {addNativeCharts} from './excel-charts.js';
const kinds={ordinary:'Sobretiempo',restday:'Descanso semanal',holiday:'Feriado',special:'Atípico'},states={requested:'Solicitado',approved:'Aprobado',taken:'Gozado',cancelled:'Cancelado'};
const date=d=>new Date(d+'T12:00:00Z');const excelDate=d=>Date.parse(d+'T00:00:00Z')/86400000+25569;const time=s=>s?((+s.slice(0,2))*60+(+s.slice(3)))/1440:null;
const days=['Domingo','Lunes','Martes','Miércoles','Jueves','Viernes','Sábado'];const weekday=d=>days[date(d).getUTCDay()];
const C={navy:'FF21374D',blue:'FF749DC1',pale:'FFEEF3F8',green:'FFE8F1EC',ink:'FF293A48',muted:'FF697887',white:'FFFFFFFF'};
export async function makeXlsx(m){const {default:ExcelJS}=await import('exceljs');const b=new ExcelJS.Workbook();b.creator='Ing. Mauro Espinoza · myk2';b.title='Informe de horas y descansos';b.subject='Compensación de horas';b.created=new Date();b.calcProperties.fullCalcOnLoad=true;
 const panel=b.addWorksheet('Panel'),evolution=b.addWorksheet('Evolución'),daily=b.addWorksheet('Registro diario'),rests=b.addWorksheet('Descansos'),ledger=b.addWorksheet('Movimientos'),params=b.addWorksheet('Parámetros');
 const sheets=[panel,evolution,daily,rests,ledger,params];for(const s of sheets){s.properties.defaultRowHeight=23;s.views=[{showGridLines:false}];s.pageSetup={paperSize:9,orientation:'landscape',fitToPage:true,fitToWidth:1,fitToHeight:0,margins:{left:.25,right:.25,top:.4,bottom:.4,header:.15,footer:.2}};s.headerFooter.oddFooter='&L© Ing. Mauro Espinoza · myk2&C'+m.created.date+' · v'+VERSION+'&RPágina &P de &N';}
 const styleCell=(cell,{fill,fontSize=11,bold=false,color=C.ink}={})=>{cell.font={name:'Aptos',size:fontSize,bold,color:{argb:color}};cell.alignment={vertical:'middle',wrapText:true,indent:1};if(fill)cell.fill={type:'pattern',pattern:'solid',fgColor:{argb:fill}};};
 const band=(s,range,text,fill=C.navy,fontSize=20,color=C.white)=>{s.mergeCells(range);const first=s.getCell(range.split(':')[0]);first.value=text;styleCell(first,{fill,fontSize,bold:true,color});};
 const title=(s,end,text,sub)=>{band(s,`A1:${end}2`,text);s.mergeCells(`A3:${end}3`);s.getCell('A3').value=sub;styleCell(s.getCell('A3'),{fontSize:11,color:C.muted});s.getRow(3).height=32;};
 const table=(s,name,columns,rows)=>{s.addTable({name,ref:'A6',headerRow:true,style:{theme:'TableStyleMedium2',showRowStripes:true},columns:columns.map(name=>({name,filterButton:true})),rows});s.getRow(6).height=32;s.getRow(6).eachCell(c=>styleCell(c,{fill:C.navy,bold:true,color:C.white}));for(let r=7;r<7+rows.length;r++){s.getRow(r).height=30;s.getRow(r).eachCell(c=>styleCell(c,{fill:r%2?C.white:C.pale}));}s.views=[{state:'frozen',ySplit:6,showGridLines:false}];s.pageSetup.printTitlesRow='1:6';};
 const profile=(m.profile.name||'Usuario')+(m.profile.company?' · '+m.profile.company:'');const period=`${m.from||'Primer registro'} a ${m.to}`;
 daily.columns=[15,16,23,20,20,18,19,18,21,18,70].map(width=>({width}));title(daily,'K','Detalle diario de horas',profile+' · '+period+' · America/Lima');
 table(daily,'Jornadas',['Fecha','Día','Tipo','Salida prevista','Inicio declarado','Salida real','Día siguiente','Pausa (min)','Extra (min)','Extra (h)','Comentario'],m.records.map((r,i)=>[date(r.date),weekday(r.date),kinds[r.kind],time(r.expected),time(r.start),time(r.end),r.nextDay?'Sí':'No',r.pause||0,r.minutes,{formula:`I${i+7}/60`,result:r.minutes/60},r.comment||'']));daily.getColumn(1).numFmt='dd/mm/yyyy';[4,5,6].forEach(c=>daily.getColumn(c).numFmt='hh:mm');daily.getColumn(10).numFmt='0.00';for(let i=0;i<m.records.length;i++)daily.getRow(i+7).height=Math.min(180,Math.max(30,Math.ceil((m.records[i].comment||'').length/65)*15));
 rests.columns=[16,17,20,20,23,75].map(width=>({width}));title(rests,'F','Descansos compensatorios',profile+' · '+period);table(rests,'Compensaciones',['Fecha','Día','Estado','Horas','Días equivalentes','Comentario'],m.rests.map((r,i)=>[date(r.date),weekday(r.date),states[r.status],r.minutes/60,{formula:`D${i+7}/'Parámetros'!$B$4`,result:r.minutes/(m.profile.dayHours*60)},r.comment||'']));rests.getColumn(1).numFmt='dd/mm/yyyy';rests.getColumn(4).numFmt='0.00';rests.getColumn(5).numFmt='0.00';for(let i=0;i<m.rests.length;i++)rests.getRow(i+7).height=Math.min(180,Math.max(30,Math.ceil((m.rests[i].comment||'').length/72)*15));
 const dr=Math.max(7,6+m.records.length),rr=Math.max(7,6+m.rests.length);const sumGenerated=`SUM('Registro diario'!J7:J${dr})`,sumUsed=`SUMIF(Descansos!C7:C${rr},"Gozado",Descansos!D7:D${rr})`,sumReserved=`SUMIF(Descansos!C7:C${rr},"Aprobado",Descansos!D7:D${rr})`;
 evolution.columns=[20,16,16,22,22,22,20,22].map(width=>({width}));title(evolution,'H','Evolución y consolidado',profile+' · '+({day:'Por día',week:'Por semana (lunes a domingo)',month:'Por mes'}[m.mode]));
 const groups=m.groups.length?m.groups:[{period:'Sin datos',earned:0,used:0,reserved:0,balance:m.opening}];const groupRows=groups.map((g,i)=>{const row=i+7;let a=g.period,bound=g.period;if(a!=='Sin datos'){if(m.mode==='month'){a+='-01';const end=new Date(a+'T12:00:00Z');end.setUTCMonth(end.getUTCMonth()+1);end.setUTCDate(0);bound=end.toISOString().slice(0,10);}else if(m.mode==='week'){const end=date(a);end.setUTCDate(end.getUTCDate()+6);bound=end.toISOString().slice(0,10);}}const valid=a!=='Sin datos';const gen=`SUMIFS('Registro diario'!$J$7:$J$${dr},'Registro diario'!$A$7:$A$${dr},">="&B${row},'Registro diario'!$A$7:$A$${dr},"<"&C${row}+1)`;const restSum=status=>`SUMIFS(Descansos!$D$7:$D$${rr},Descansos!$A$7:$A$${rr},">="&B${row},Descansos!$A$7:$A$${rr},"<"&C${row}+1,Descansos!$C$7:$C$${rr},"${status}")`;return [g.period,valid?date(a):null,valid?date(bound):null,valid?{formula:gen,result:g.earned/60}:0,valid?{formula:restSum('Gozado'),result:g.used/60}:0,valid?{formula:restSum('Aprobado'),result:g.reserved/60}:0,{formula:`D${row}-E${row}`,result:(g.earned-g.used)/60},{formula:`'Parámetros'!$B$5+SUM($G$7:G${row})`,result:g.balance/60}];});table(evolution,'Consolidado',['Período','Desde','Hasta','Generadas (h)','Gozadas (h)','Reservadas (h)','Neto (h)','Saldo (h)'],groupRows);[2,3].forEach(c=>evolution.getColumn(c).numFmt='dd/mm/yyyy');[4,5,6,7,8].forEach(c=>evolution.getColumn(c).numFmt='0.00');
 ledger.columns=[17,26,22,22,22,80].map(width=>({width}));title(ledger,'F','Movimientos de saldo',profile+' · '+period+' · Incluye apertura anterior al período');table(ledger,'MovimientosSaldo',['Fecha','Movimiento','Ingreso (h)','Descuento (h)','Saldo (h)','Referencia / comentario'],m.movements.map((r,i)=>[date(r.date),r.type,r.credit/60,r.debit/60,{formula:i?`E${i+6}+C${i+7}-D${i+7}`:`'Parámetros'!$B$5+C7-D7`,result:r.balance/60},r.comment]));ledger.getColumn(1).numFmt='dd/mm/yyyy';[3,4,5].forEach(c=>ledger.getColumn(c).numFmt='0.00');
 params.columns=[43,30,55].map(width=>({width}));title(params,'C','Parámetros y criterios',profile);const values=[['Horas por día de descanso',m.profile.dayHours],['Saldo anterior al período (h)',m.opening/60],['Gozadas históricas al cierre (h)',{formula:`${(m.closing.used-m.period.used)/60}+${sumUsed}`,result:m.closing.used/60}],['Reservadas históricas al cierre (h)',{formula:`${(m.closing.reserved-m.period.reserved)/60}+${sumReserved}`,result:m.closing.reserved/60}],['Generadas históricas al cierre (h)',{formula:`${(m.closing.earned-m.period.earned)/60}+${sumGenerated}`,result:m.closing.earned/60}],['Fecha inicial',m.from||'Primer registro'],['Fecha de cierre',date(m.to)],['Emisión (Lima)',`${m.created.date} ${m.created.time}`]];values.forEach((r,i)=>{params.getCell(i+4,1).value=r[0];params.getCell(i+4,2).value=r[1];styleCell(params.getCell(i+4,1),{bold:true});styleCell(params.getCell(i+4,2),{fill:C.pale,color:'FF356A9A'});if(typeof r[1]==='number'||r[1]?.formula)params.getCell(i+4,2).numFmt='0.00';});params.getCell('B10').numFmt='dd/mm/yyyy';params.getCell('A13').value='Distribución histórica (gráfico)';styleCell(params.getCell('A13'),{bold:true});[['Gozadas',{formula:'B6',result:m.closing.used/60}],['Reservadas',{formula:'B7',result:m.closing.reserved/60}],['Libres',{formula:'MAX(0,B8-B6-B7)',result:Math.max(0,m.closing.available)/60}]].forEach((r,i)=>{params.getCell(i+14,1).value=r[0];params.getCell(i+14,2).value=r[1];params.getCell(i+14,2).numFmt='0.00';});
 const notes=['Compensación 1:1 según acuerdo. Equivalencia configurable; no determina la legalidad de la jornada.','Solicitado: no descuenta. Aprobado: reserva. Gozado: descuenta. Cancelado: libera.','Las fechas del período se aplican a la fecha de jornada o descanso, en hora de Lima.','Los valores históricos anteriores al período son una instantánea del registro al emitir este archivo.','Los gráficos son nativos de Excel y pueden editarse. Las fórmulas recalculan dentro de los rangos exportados.','Si agregas filas nuevas en Excel, revisa y amplía los rangos de fórmulas y gráficos.','La hoja Movimientos refleja el orden cronológico al exportar; no la reordenes sin revisar el saldo.','Domingos y feriados se distinguen del sobretiempo ordinario. No se calculan pagos ni recargos.','Fuente: registros ingresados por el usuario. Guía MTPE: www.gob.pe/institucion/mtpe/informes-publicaciones/6199835-como-calcular-las-horas-extras','© Ing. Mauro Espinoza · myk2 · mespinozahse@gmail.com · +51 975721020'];notes.forEach((t,i)=>{params.mergeCells(`A${19+i}:C${19+i}`);params.getCell(19+i,1).value=t;styleCell(params.getCell(19+i,1),{fontSize:10,color:C.muted});params.getRow(19+i).height=35;});
 panel.columns=Array.from({length:14},()=>({width:12}));title(panel,'N','myk2 · Informe ejecutivo',profile+' · '+period);panel.mergeCells('A4:N4');panel.getCell('A4').value=`Emitido ${m.created.date} ${m.created.time} (Lima) · ${m.records.length} jornadas · ${m.rests.length} descansos · v${VERSION}`;styleCell(panel.getCell('A4'),{fontSize:10,color:C.muted});
 const kpi=(a,b,label,formula,value,format='0.00 "h"',accent=false)=>{band(panel,`${a}6:${b}6`,label,accent?C.navy:C.pale,11,accent?C.white:C.muted);panel.mergeCells(`${a}7:${b}9`);const c=panel.getCell(`${a}7`);c.value={formula,result:value};c.numFmt=format;styleCell(c,{fill:accent?C.navy:C.pale,fontSize:28,bold:true,color:accent?'FFC6DDEF':C.navy});c.alignment={vertical:'middle',horizontal:'left',indent:1};};
 kpi('A','D','SALDO AL CIERRE',`'Parámetros'!B5+${sumGenerated}-${sumUsed}`,m.closing.balance/60,'0.00 "h"',true);kpi('E','G','DÍAS EQUIVALENTES',`A7/'Parámetros'!B4`,m.equivalent.decimal,'0.00 "días"');kpi('H','J','GENERADAS / PERÍODO',sumGenerated,m.period.earned/60);kpi('K','N','GOZADAS / PERÍODO',sumUsed,m.period.used/60);
 const small=(range,value)=>{panel.mergeCells(range);const c=panel.getCell(range.split(':')[0]);c.value=value;styleCell(c,{fill:C.green,fontSize:11});};small('A11:D12',`Apertura: ${(m.opening/60).toFixed(2)} h`);small('E11:G12',`Reservadas al cierre: ${(m.closing.reserved/60).toFixed(2)} h`);small('H11:J12',`Libres: ${(m.closing.available/60).toFixed(2)} h`);small('K11:N12',`${m.profile.dayHours} h = 1 día de referencia`);
 band(panel,'A32:N32','RESUMEN AL EMITIR EL INFORME',C.navy,12);panel.mergeCells('A33:N34');panel.getCell('A33').value=`${m.records.length} jornadas generaron ${(m.period.earned/60).toFixed(2)} h. Se gozaron ${(m.period.used/60).toFixed(2)} h. El saldo libre histórico al cierre es ${(m.closing.available/60).toFixed(2)} h después de las reservas.`;styleCell(panel.getCell('A33'),{fontSize:12});panel.mergeCells('A36:N37');panel.getCell('A36').value='Consulta Evolución para el consolidado; Registro diario y Descansos para el detalle; Movimientos para seguir el saldo; Parámetros para las reglas y datos históricos.';styleCell(panel.getCell('A36'),{fontSize:11,color:C.muted});panel.mergeCells('A39:N40');panel.getCell('A39').value='© Ing. Mauro Espinoza · myk2 · mespinozahse@gmail.com · +51 975721020\nRegistro de compensación acordada. No es una liquidación laboral.';styleCell(panel.getCell('A39'),{fontSize:10,color:C.muted});panel.pageSetup.printArea='A1:N40';panel.pageSetup.fitToHeight=1;
 return addNativeCharts(await b.xlsx.writeBuffer(),m);
}
