import {duration,VERSION} from './core.js';
const kinds={ordinary:'Sobretiempo',restday:'Descanso semanal',holiday:'Feriado',special:'Atípico'},states={requested:'Solicitado',approved:'Aprobado',taken:'Gozado',cancelled:'Cancelado'};
const colors={navy:[33,55,77],blue:[116,157,193],pale:[239,244,249],muted:[105,120,135],ink:[41,58,72],green:[148,187,165],gold:[209,183,129]};
const safe=s=>String(s??'').replace(/[−–—]/g,'-');
export async function makePdf(m){const [{jsPDF},{default:autoTable}]=await Promise.all([import('jspdf'),import('jspdf-autotable')]);const d=new jsPDF({orientation:'landscape',unit:'mm',format:'a4'});const W=297,H=210;
 const txt=(text,x,y,size=10,color=colors.ink,bold=false)=>{d.setFont('helvetica',bold?'bold':'normal');d.setFontSize(size);d.setTextColor(...color);d.text(safe(text),x,y);};
 const box=(x,y,w,h,color=colors.pale)=>{d.setFillColor(...color);d.roundedRect(x,y,w,h,3,3,'F');};
 const header=(title,subtitle)=>{d.setFillColor(...colors.navy);d.rect(0,0,W,34,'F');txt('myk2 / TIEMPO',13,11,10,[191,215,238],true);txt(title,13,24,20,[255,255,255],true);txt(subtitle,13,42,10,colors.muted);};
 const period=`${m.from||'Primer registro'}  a  ${m.to}  |  ${ {day:'Detalle diario',week:'Semanas de lunes a domingo',month:'Vista mensual'}[m.mode]}`;
 const profile=`${m.profile.name||'Usuario'}${m.profile.company?' / '+m.profile.company:''}`;
 const newPage=(title,sub)=>{d.addPage();header(title,sub);};
 const section=(title,x,y)=>txt(title,x,y,12,colors.navy,true);
 const card=(x,label,value,sub)=>{box(x,53,64,32);txt(label,x+5,61,9,colors.muted);txt(value,x+5,72,20,colors.navy,true);txt(sub,x+5,79,8,colors.muted);};
 header('Informe ejecutivo de horas y descansos',period);txt(profile,13,48,10,colors.ink,true);
 card(13,'SALDO AL CIERRE',`${(m.closing.balance/60).toFixed(2)} h`,duration(m.closing.balance));card(82,'DESCANSO EQUIVALENTE',`${m.equivalent.decimal.toFixed(2)} días`,`${m.equivalent.days} días + ${duration(m.equivalent.remainder)}`);card(151,'GENERADAS EN EL PERÍODO',`${(m.period.earned/60).toFixed(2)} h`,`${m.records.length} jornadas registradas`);card(220,'GOZADAS EN EL PERÍODO',`${(m.period.used/60).toFixed(2)} h`,`${m.rests.filter(r=>r.status==='taken').length} descansos gozados`);
 section('Evolución del tiempo',13,98);txt('Generadas vs. gozadas / horas decimales',13,105,8,colors.muted);
 const g=m.groups.slice(-12),max=Math.max(1,...g.map(x=>Math.max(x.earned,x.used)/60));const top=112,bottom=155,left=24,right=181;
 d.setDrawColor(224,231,237);d.setLineWidth(.2);for(let i=0;i<=4;i++){const y=bottom-(bottom-top)*i/4;d.line(left,y,right,y);txt((max*i/4).toFixed(1),13,y+1,7,colors.muted);}
 const slot=(right-left)/Math.max(1,g.length);g.forEach((r,i)=>{const x=left+i*slot+slot*.18;const bw=Math.min(6,slot*.27);d.setFillColor(...colors.blue);d.roundedRect(x,bottom-(r.earned/60/max)*(bottom-top),bw,Math.max(.1,r.earned/60/max*(bottom-top)),.6,.6,'F');d.setFillColor(...colors.navy);d.roundedRect(x+bw+1,bottom-(r.used/60/max)*(bottom-top),bw,Math.max(.1,r.used/60/max*(bottom-top)),.6,.6,'F');txt(r.period.slice(5),x-1,bottom+6,6.5,colors.muted);});if(!g.length)txt('Aún no hay movimientos en este período.',50,135,10,colors.muted);
 d.setFillColor(...colors.blue);d.rect(27,168,3,3,'F');txt('Generadas',33,171,8,colors.muted);d.setFillColor(...colors.navy);d.rect(67,168,3,3,'F');txt('Gozadas',73,171,8,colors.muted);txt(g.length<m.groups.length?'Últimos 12 períodos; el consolidado incluye todos.':'Todos los períodos con movimientos.',13,179,8,colors.muted);
 section('Distribución histórica al cierre',198,98);const vals=[m.closing.used,m.closing.reserved,Math.max(0,m.closing.available)],pal=[colors.navy,colors.gold,colors.green],total=vals.reduce((a,b)=>a+b,0);let angle=-Math.PI/2;const cx=234,cy=133,r=23;
 if(!total){d.setFillColor(230,236,241);d.circle(cx,cy,r,'F');}else vals.forEach((v,i)=>{const span=v/total*Math.PI*2;d.setFillColor(...pal[i]);d.setDrawColor(...pal[i]);d.setLineWidth(.08);for(let a=angle;a<angle+span-.00001;a+=.06){const b=Math.min(a+.061,angle+span);d.triangle(cx,cy,cx+r*Math.cos(a),cy+r*Math.sin(a),cx+r*Math.cos(b),cy+r*Math.sin(b),'FD');}angle+=span;});d.setFillColor(255);d.circle(cx,cy,16,'F');txt((Math.max(0,m.closing.available)/60).toFixed(1)+' h',cx-11,cy+1,13,colors.navy,true);txt('libres',cx-6,cy+6,8,colors.muted);
 ['Gozadas','Reservadas','Libres'].forEach((name,i)=>{const y=165+i*7;d.setFillColor(...pal[i]);d.rect(200,y-2.5,3,3,'F');txt(name,206,y,8,colors.muted);txt(duration(vals[i]),247,y,8,colors.ink,true);});
 box(13,184,270,8);txt(`Saldo inicial: ${duration(m.opening)}    +    Generadas: ${duration(m.period.earned)}    -    Gozadas: ${duration(m.period.used)}    =    Cierre: ${duration(m.closing.balance)}`,17,189.5,9,colors.navy,true);
 const table=(head,body,start=52,widths)=>autoTable(d,{startY:start,head:[head],body,margin:{top:49,left:13,right:13,bottom:19},styles:{font:'helvetica',fontSize:8.5,cellPadding:3,textColor:colors.ink,lineColor:[229,235,239],lineWidth:.12,overflow:'linebreak'},headStyles:{fillColor:colors.navy,textColor:[255,255,255],fontStyle:'bold'},alternateRowStyles:{fillColor:[244,247,250]},columnStyles:widths||{},didDrawPage:()=>{if(d.internal.getCurrentPageInfo().pageNumber>1){/* Encabezado de tabla repetido por AutoTable. */}}});
 newPage('Consolidado del período',`${profile} / ${period}`);txt(`Apertura: ${duration(m.opening)}   |   Neto del período: ${duration(m.period.earned-m.period.used)}   |   Cierre: ${duration(m.closing.balance)}`,13,49,10,colors.navy,true);
 table(['Período','Generadas (h)','Gozadas (h)','Reservadas (h)','Neto (h)','Saldo (h)','Saldo (días)'],m.groups.map(r=>[r.period,(r.earned/60).toFixed(2),(r.used/60).toFixed(2),(r.reserved/60).toFixed(2),((r.earned-r.used)/60).toFixed(2),(r.balance/60).toFixed(2),(r.balance/(m.profile.dayHours*60)).toFixed(2)]),56);
 let y=d.lastAutoTable.finalY+13;if(y>155){newPage('Criterios del consolidado',profile);y=55;}section('Lectura del saldo',13,y);txt('Aprobado reserva horas; únicamente Gozado descuenta. Solicitado y Cancelado no descuentan.',13,y+8,9,colors.muted);txt(`Equivalencia utilizada: ${m.profile.dayHours} horas = 1 día. La equivalencia refleja tu configuración.`,13,y+15,9,colors.muted);txt('El saldo al cierre incluye movimientos anteriores al período. Las reservas mostradas arriba corresponden al período.',13,y+22,9,colors.muted);txt('Los gráficos de evolución muestran horas decimales: 1.50 h equivale a 1 h 30 min.',13,y+29,9,colors.muted);
 newPage('Detalle de jornadas',`${profile} / ${m.records.length} registros / ${period}`);
 table(['Fecha','Tipo','Intervalo registrado','Pausa (min)','Extra (h)','Comentario'],m.records.map(r=>[r.date,kinds[r.kind],`${r.kind==='ordinary'?'Desde salida prevista':'Desde inicio'} ${r.kind==='ordinary'?r.expected:r.start}\nHasta ${r.end}${r.nextDay?' (+1 día)':''}`,r.pause||0,(r.minutes/60).toFixed(2),safe(r.comment||'-')]),52,{0:{cellWidth:24},1:{cellWidth:30},2:{cellWidth:49},3:{cellWidth:22},4:{cellWidth:22},5:{cellWidth:124}});
 newPage('Descansos y compensaciones',`${profile} / Estados registrados por el usuario`);
 txt(`Solicitadas: ${duration(m.requested)}  |  Reservadas: ${duration(m.period.reserved)}  |  Gozadas: ${duration(m.period.used)}  |  Canceladas: ${duration(m.cancelled)}`,13,49,9,colors.navy,true);
 table(['Fecha','Estado','Horas','Días equivalentes','Comentario'],m.rests.map(r=>[r.date,states[r.status],(r.minutes/60).toFixed(2),(r.minutes/(m.profile.dayHours*60)).toFixed(2),safe(r.comment||'-')]),56,{0:{cellWidth:26},1:{cellWidth:31},2:{cellWidth:25},3:{cellWidth:35},4:{cellWidth:154}});
 newPage('Movimientos y trazabilidad del saldo',`${profile} / Entradas y descuentos ordenados por fecha`);txt(`Saldo de apertura: ${duration(m.opening)}`,13,49,10,colors.navy,true);
 table(['Fecha','Movimiento','Ingreso (h)','Descuento (h)','Saldo (h)','Referencia / comentario'],m.movements.map(r=>[r.date,r.type,r.credit?(r.credit/60).toFixed(2):'-',r.debit?(r.debit/60).toFixed(2):'-',(r.balance/60).toFixed(2),safe(r.comment||'-')]),56,{0:{cellWidth:25},1:{cellWidth:37},2:{cellWidth:25},3:{cellWidth:27},4:{cellWidth:25},5:{cellWidth:132}});
 const n=d.getNumberOfPages();for(let i=1;i<=n;i++){d.setPage(i);d.setDrawColor(218,226,234);d.line(13,195,284,195);txt(`© Ing. Mauro Espinoza / myk2 / mespinozahse@gmail.com / +51 975721020 / v${VERSION}`,13,200,7.5,colors.muted);txt(`${i} / ${n}`,273,200,8,colors.muted);txt(`Emitido ${m.created.date} ${m.created.time} (Lima). Registro de compensación; no es una liquidación laboral.`,13,205,7,colors.muted);}
 return d;
}
