import {createClient} from '@supabase/supabase-js';
import {defaults} from './core.js';
const url=import.meta.env.VITE_SUPABASE_URL,key=import.meta.env.VITE_SUPABASE_ANON_KEY;
export const cloud=url&&key?createClient(url,key):null;
const LOCAL_KEY='myk2-tiempo-v1';
export let user=null,admin=false,role='user',companyId=null,target=null;
export let data={profile:{...defaults},records:[],rests:[]};
export async function init(){if(cloud){const {data:s,error}=await cloud.auth.getSession();if(error)throw error;user=s.session?.user||null;if(user){target=user.id;await load();}}else{const raw=localStorage.getItem(LOCAL_KEY);if(raw){const parsed=JSON.parse(raw);data={profile:{...defaults,...parsed.profile},records:parsed.records||[],rests:parsed.rests||[]};}}}
async function allRows(table){let rows=[],offset=0;while(true){const {data:part,error}=await cloud.from(table).select('*').eq('user_id',target).order('id').range(offset,offset+999);if(error)throw error;rows.push(...part);if(part.length<1000)return rows;offset+=1000;}}
export async function load(){const [p,r,s,a,c]=await Promise.all([cloud.from('profiles').select('*').eq('id',target).single(),allRows('entries'),allRows('rests'),cloud.rpc('is_admin'),cloud.rpc('access_context')]);if(p.error)throw p.error;if(a.error)throw a.error;if(c.error)throw c.error;admin=a.data===true;role=c.data?.role||'user';companyId=c.data?.company_id||null;data={profile:{...defaults,...p.data.settings,firstName:p.data.first_name||'',lastName:p.data.last_name||'',name:p.data.name||[p.data.first_name,p.data.last_name].filter(Boolean).join(' '),company:p.data.company,companyId:p.data.company_id||companyId,documentType:p.data.document_type||'DNI',documentNumber:p.data.document_number||'',phone:p.data.phone},records:r.map(x=>({...x.payload,id:x.id,date:x.date,minutes:x.minutes})),rests:s.map(x=>({...x.payload,id:x.id,date:x.date,minutes:x.minutes,status:x.status}))};}
export async function selectUser(id){target=id;await load();}
function persist(next){localStorage.setItem(LOCAL_KEY,JSON.stringify(next));data=next;}
export async function saveProfile(profile){if(cloud){const {error}=await cloud.from('profiles').update({name:profile.name,first_name:profile.firstName,last_name:profile.lastName,company:profile.company,document_type:profile.documentType,document_number:profile.documentNumber,phone:profile.phone,settings:{dayHours:profile.dayHours,schedule:profile.schedule}}).eq('id',target);if(error)throw error;data.profile=profile;}else persist({...data,profile});}
export async function saveItem(collection,item){const existing=data[collection].some(r=>r.id===item.id);const next={...data,[collection]:[...data[collection].filter(r=>r.id!==item.id),item].sort((a,b)=>a.date.localeCompare(b.date))};if(cloud){const table=cloud.from(collection==='records'?'entries':'rests');const row={id:item.id,user_id:target,date:item.date,minutes:item.minutes,...(collection==='rests'?{status:item.status}:{}),payload:item};const query=existing?table.update(row).eq('id',item.id).eq('user_id',target):table.insert(row);const {data:saved,error}=await query.select('id').single();if(error)throw error;if(!saved)throw Error('El registro cambió en otro equipo. Recarga antes de intentar otra vez.');data=next;}else persist(next);}
export async function removeItem(collection,id){if(cloud){const {error}=await cloud.from(collection==='records'?'entries':'rests').delete().eq('id',id).eq('user_id',target);if(error)throw error;data={...data,[collection]:data[collection].filter(r=>r.id!==id)};}else persist({...data,[collection]:data[collection].filter(r=>r.id!==id)});}
export async function users(){const {data,error}=await cloud.from('profiles').select('id,name,company').order('name');if(error)throw error;return data;}
export async function companies(){if(!cloud)return[];const {data,error}=await cloud.rpc('list_companies');if(error)throw error;return data||[];}
export async function createCompany(name){const {error}=await cloud.rpc('developer_create_company',{p_name:name});if(error)throw error;}
export async function assignRole(email,nextRole,nextCompany){const {error}=await cloud.rpc('developer_assign_role',{p_email:email,p_role:nextRole,p_company:nextCompany});if(error)throw error;}
export async function signout(){if(cloud){await cloud.auth.signOut();user=null;admin=false;role='user';companyId=null;target=null;data={profile:{...defaults},records:[],rests:[]};}}

